name: isar_key_value
description: A super fast key value store built on top of the isar database.
version: 0.3.0+1
repository: https://github.com/MohiuddinM/isar_key_value

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  # Using the isar-community.dev because the official isar package is not updated
  isar:
    hosted:
      name: isar
      url: https://pub.isar-community.dev/
    version: ^3.0.0
  isar_flutter_libs:
    hosted:
      name: isar_flutter_libs
      url: https://pub.isar-community.dev/
    version: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.0.0
  isar_generator:
    hosted:
      name: isar_generator
      url: https://pub.isar-community.dev/
  build_runner: ^2.0.0
